apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: redis:latest
        ports:
        - containerPort: 80
